// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: geo_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The Input
type TileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	ImageData     []byte                 `protobuf:"bytes,4,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"` // The raw pixel bytes
	ModelType     string                 `protobuf:"bytes,5,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"` // "cloud_mask" or "ndvi"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TileRequest) Reset() {
	*x = TileRequest{}
	mi := &file_geo_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TileRequest) ProtoMessage() {}

func (x *TileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geo_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TileRequest.ProtoReflect.Descriptor instead.
func (*TileRequest) Descriptor() ([]byte, []int) {
	return file_geo_service_proto_rawDescGZIP(), []int{0}
}

func (x *TileRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TileRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *TileRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TileRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *TileRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

// The Output
type TileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ResultData    []byte                 `protobuf:"bytes,3,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"` // The processed mask
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TileResponse) Reset() {
	*x = TileResponse{}
	mi := &file_geo_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TileResponse) ProtoMessage() {}

func (x *TileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geo_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TileResponse.ProtoReflect.Descriptor instead.
func (*TileResponse) Descriptor() ([]byte, []int) {
	return file_geo_service_proto_rawDescGZIP(), []int{1}
}

func (x *TileResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TileResponse) GetResultData() []byte {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *TileResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_geo_service_proto protoreflect.FileDescriptor

const file_geo_service_proto_rawDesc = "" +
	"\n" +
	"\x11geo_service.proto\x12\vgeoanalysis\"\x98\x01\n" +
	"\vTileRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1d\n" +
	"\n" +
	"image_data\x18\x04 \x01(\fR\timageData\x12\x1d\n" +
	"\n" +
	"model_type\x18\x05 \x01(\tR\tmodelType\"\x8d\x01\n" +
	"\fTileResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_data\x18\x03 \x01(\fR\n" +
	"resultData\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage2S\n" +
	"\rImageAnalyzer\x12B\n" +
	"\vAnalyzeTile\x12\x18.geoanalysis.TileRequest\x1a\x19.geoanalysis.TileResponseB\x17Z\x15sat-vis/go-api/pkg/pbb\x06proto3"

var (
	file_geo_service_proto_rawDescOnce sync.Once
	file_geo_service_proto_rawDescData []byte
)

func file_geo_service_proto_rawDescGZIP() []byte {
	file_geo_service_proto_rawDescOnce.Do(func() {
		file_geo_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geo_service_proto_rawDesc), len(file_geo_service_proto_rawDesc)))
	})
	return file_geo_service_proto_rawDescData
}

var file_geo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_geo_service_proto_goTypes = []any{
	(*TileRequest)(nil),  // 0: geoanalysis.TileRequest
	(*TileResponse)(nil), // 1: geoanalysis.TileResponse
}
var file_geo_service_proto_depIdxs = []int32{
	0, // 0: geoanalysis.ImageAnalyzer.AnalyzeTile:input_type -> geoanalysis.TileRequest
	1, // 1: geoanalysis.ImageAnalyzer.AnalyzeTile:output_type -> geoanalysis.TileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_geo_service_proto_init() }
func file_geo_service_proto_init() {
	if File_geo_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geo_service_proto_rawDesc), len(file_geo_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geo_service_proto_goTypes,
		DependencyIndexes: file_geo_service_proto_depIdxs,
		MessageInfos:      file_geo_service_proto_msgTypes,
	}.Build()
	File_geo_service_proto = out.File
	file_geo_service_proto_goTypes = nil
	file_geo_service_proto_depIdxs = nil
}
